### ISSUE TITLE
Successor for pylint-pytest

### ISSUE THREAD

**Issue by kasium** [DanielNoord/pylint-pytest-plugin#15]
Hi,
I used [pylint-pytest](https://pypi.org/project/pylint-pytest/) up to now, but the repository vanished from GitHub.
Is this plugin the logical successor of it?

**Comment by DanielNoord** [comment]
I think so, although it probably doesn't have 100% feature parity.

Feel free to open an issue about missing features!

**Comment by kasium** [comment]
@DanielNoord great!
Here is one important difference: pytest allows you to define fixtures in other files or plugins (e.g. conftest.py). This is currently not supported. pylint-pytest solved that by getting all fixtures inside the current files scope. This has however major drawbacks and also has a performance implication. Do you have something in mind?

**Comment by DanielNoord** [comment]
@kasium This sounds like a very good use case, would you mind opening a specific issue for this? Preferably with some "test code", that really helps with implementing!

**Comment by kasium** [comment]
@DanielNoord will do that!
